I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script
    define config.mouse_callbacks = False
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
Exception: config.mouse_callbacks is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script
    define config.mouse_callbacks = False
  File "C:\Users\game\Desktop\renpy-8.2.0-sdk\renpy\ast.py", line 2219, in execute
    self.set()
  File "C:\Users\game\Desktop\renpy-8.2.0-sdk\renpy\ast.py", line 2237, in set
    ns.set(self.varname, value)
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
  File "C:\Users\game\Desktop\renpy-8.2.0-sdk\renpy\defaultstore.py", line 101, in __setattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.mouse_callbacks is not a known configuration variable.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
visual novel 1.0
Wed Feb  7 09:57:54 2024
